import { Team } from 'types';

const TEAMS: Team[] = [
  {
    teamName: 'GEN.G',
    teamNameKorean: '젠지 이스포츠',
    teamNameShort: 'GEN',
    teamId: 'gen',
    firstColor: '#000000',
    secondColor: '#aa8a00',
  },
  {
    teamName: 'T1',
    teamNameKorean: '티원',
    teamNameShort: 'T1',
    teamId: 't1',
    firstColor: '#e4002b',
    secondColor: '#000000',
  },
  {
    teamName: 'Liiv SANDBOX',
    teamNameKorean: '리브 샌드박스',
    teamNameShort: 'LSB',
    teamId: 'lsb',
    firstColor: '#ffc900',
    secondColor: '#000000',
  },
  {
    teamName: 'DWG KIA',
    teamNameKorean: '담원 기아',
    teamNameShort: 'DK',
    teamId: 'dk',
    firstColor: '#000000',
    secondColor: '#0ec7b5',
  },
  {
    teamName: 'KT Rolster',
    teamNameKorean: '케이티 롤스터',
    teamNameShort: 'KT',
    teamId: 'kt',
    firstColor: '#000000',
    secondColor: '#ff0a07',
  },
  {
    teamName: 'DRX',
    teamNameKorean: '디알엑스',
    teamNameShort: 'DRX',
    teamId: 'drx',
    firstColor: '#5a8dff',
    secondColor: '#2f5ff7',
  },
  {
    teamName: 'Kwangdong Freecs',
    teamNameKorean: '광동 프릭스',
    teamNameShort: 'KDF',
    teamId: 'kdf',
    firstColor: '#e73312',
    secondColor: '#585858',
  },
  {
    teamName: 'NongShim Redforce',
    teamNameKorean: '농심 레드포스',
    teamNameShort: 'NS',
    teamId: 'ns',
    firstColor: '#de2027',
    secondColor: '#ffffff',
  },
  {
    teamName: 'Fredit BRION',
    teamNameKorean: '프레딧 브리온',
    teamNameShort: 'BRO',
    teamId: 'bro',
    firstColor: '#00492b',
    secondColor: '#003327',
  },
  {
    teamName: 'Hanhwa Life Esports',
    teamNameKorean: '한화생명 이스포츠',
    teamNameShort: 'HLE',
    teamId: 'hle',
    firstColor: '#ff6b01',
    secondColor: '#ffffff',
  },
  {
    teamName: 'FA',
    teamNameKorean: 'FA',
    teamNameShort: 'FA',
    teamId: 'fa',
    firstColor: '#1c192b',
    secondColor: '#6454ed',
  },
];

export default TEAMS;
