const Transfer = [
  {
    playerId: 'Ray',
    name: '전지원',
    before: '1907 Fenerbahçe Espor',
    beforeShort: 'FB',
    beforeLeague: 'TCL',
    after: 'FA',
    lane: 'TOP',
    refreshedAt: '2022-03-02',
  },
  {
    playerId: 'Luci',
    name: '한창훈',
    before: 'All Knights',
    beforeShort: 'AK',
    beforeLeague: 'LLA',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-05-07',
  },
  {
    playerId: 'CaD',
    name: '조성용',
    before: 'All Knights',
    beforeShort: 'AK',
    beforeLeague: 'LLA',
    after: 'FA',
    lane: 'JUN',
    refreshedAt: '2022-05-07',
  },
  {
    playerId: 'Hoglet',
    name: '김광협',
    before: 'All Knights',
    beforeShort: 'AK',
    beforeLeague: 'LLA',
    after: 'FA',
    lane: 'JUN',
    refreshedAt: '2022-03-10',
  },
  {
    playerId: 'Motive',
    name: '조세희',
    before: 'Beşiktaş Esports',
    beforeShort: 'BJK',
    beforeLeague: 'TCL',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-02-07',
  },
  {
    playerId: 'Eign',
    name: '정희준',
    before: 'DRX Challengers',
    beforeShort: 'DRX(CL)',
    beforeLeague: 'DRX(CL)',
    after: 'FA',
    lane: 'MID',
    refreshedAt: '2022-03-03',
  },
  {
    playerId: 'Peach',
    name: '이민규',
    before: 'DRX Challengers',
    beforeShort: 'DRX(CL)',
    beforeLeague: 'DRX(CL)',
    after: 'FA',
    lane: 'JUN',
    refreshedAt: '2022-05-19',
  },
  {
    playerId: 'Kingdom',
    name: '김성권',
    before: 'DWG KIA Challengers',
    beforeShort: 'DK(CL)',
    beforeLeague: 'DK(CL)',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-05-30',
  },
  {
    playerId: 'Bvoy',
    name: '주영훈',
    before: 'Estral Esports',
    beforeShort: 'EST',
    beforeLeague: 'LLA',
    after: 'FA',
    lane: 'BOT',
    refreshedAt: '2022-04-20',
  },
  {
    playerId: 'Kuri',
    name: '최원영',
    before: 'Flamengo Los Grandes',
    beforeShort: 'FLG',
    beforeLeague: 'CBLOL',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-07-08',
  },
  {
    playerId: 'Geum Go',
    name: '김승호',
    before: 'Flamengo Los Grandes',
    beforeShort: 'FLG',
    beforeLeague: 'CBLOL',
    after: 'FA',
    lane: 'JUN',
    refreshedAt: '2022-07-08',
  },
  {
    playerId: 'Loopy',
    name: '김동현',
    before: 'Fredit BRION Challengers',
    beforeShort: 'BRO(CL)',
    beforeLeague: 'BRO(CL)',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-08-13',
  },
  {
    playerId: 'SPARKLE',
    name: '배성우',
    before: 'Galakticos',
    beforeShort: 'GAL',
    beforeLeague: 'TCL',
    after: 'FA',
    lane: 'MID',
    refreshedAt: '2022-05-25',
  },
  {
    playerId: 'Olleh',
    name: '김주성',
    before: 'Golden Guardians',
    beforeShort: 'GG',
    beforeLeague: 'LCS',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-10-23',
  },
  {
    playerId: 'DaJeung',
    name: '정다원',
    before: 'Gravitas',
    beforeShort: 'GRV',
    beforeLeague: 'LCO',
    after: 'FA',
    lane: 'MID',
    refreshedAt: '2022-10-30',
  },
  {
    playerId: 'Jelly',
    name: '손호경',
    before: 'Isurus',
    beforeShort: 'ISG',
    beforeLeague: 'LLA',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-11-22',
  },
  {
    playerId: 'SCOTT',
    name: '이해봉',
    before: 'Kanga Esports',
    beforeShort: 'KNG',
    beforeLeague: 'LCO',
    after: 'FA',
    lane: 'JUN',
    refreshedAt: '2022-05-22',
  },
  {
    playerId: 'MapSSi',
    name: '김도영',
    before: 'KDF Challengers',
    beforeShort: 'KDF(CL)',
    beforeLeague: 'KDF(CL)',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-11-21',
  },
  {
    playerId: 'Valkyrie',
    name: '고준영',
    before: 'KDF Challengers',
    beforeShort: 'KDF(CL)',
    beforeLeague: 'KDF(CL)',
    after: 'FA',
    lane: 'BOT',
    refreshedAt: '2022-06-02',
  },
  {
    playerId: 'Leo',
    name: '한겨레',
    before: 'KWANGDONG FREECS',
    beforeShort: 'KDF',
    beforeLeague: 'KDF',
    after: 'FA',
    lane: 'BOT',
    refreshedAt: '2022-10-24',
  },
  {
    playerId: 'Howling',
    name: '전호빈',
    before: 'Liiv SANDBOX',
    beforeShort: 'SB',
    beforeLeague: 'SB',
    after: 'FA',
    lane: 'TOP',
    refreshedAt: '2022-05-20',
  },
  {
    playerId: 'Sherlock',
    name: '송준희',
    before: 'Liiv SANDBOX Challengers',
    beforeShort: 'SB(CL)',
    beforeLeague: 'SB(CL)',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-10-24',
  },
  {
    playerId: 'Prove',
    name: '손민형',
    before: 'Liiv SANDBOX Challengers',
    beforeShort: 'SB(CL)',
    beforeLeague: 'SB(CL)',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-07-11',
  },
  {
    playerId: 'Ten10',
    name: '강준',
    before: 'Liiv SANDBOX Challengers',
    beforeShort: 'SB(CL)',
    beforeLeague: 'SB(CL)',
    after: 'FA',
    lane: 'JUN',
    refreshedAt: '2022-07-11',
  },
  {
    playerId: 'RangJun',
    name: '김상준',
    before: 'Mirage Elyandra',
    beforeShort: 'ME',
    beforeLeague: 'LFL',
    after: 'FA',
    lane: 'MID',
    refreshedAt: '2022-01-13',
  },
  {
    playerId: 'HiRit',
    name: '신태민',
    before: 'Misfits Gaming',
    beforeShort: 'MSF',
    beforeLeague: 'LEC',
    after: 'FA',
    lane: 'TOP',
    refreshedAt: '2022-05-31',
  },
  {
    playerId: 'Ruin',
    name: '김형민',
    before: 'NASR ESPORTS',
    beforeShort: 'NSR',
    beforeLeague: 'TCL',
    after: 'FA',
    lane: 'TOP',
    refreshedAt: '2022-05-30',
  },
  {
    playerId: 'Pout',
    name: '한인웅',
    before: 'Papara SuperMassive Blaze',
    beforeShort: 'SMB',
    beforeLeague: 'TCL',
    after: 'FA',
    lane: 'MID',
    refreshedAt: '2022-06-29',
  },
  {
    playerId: 'Bay',
    name: '박준병',
    before: 'PSG Talon',
    beforeShort: 'PSG',
    beforeLeague: 'PCS',
    after: 'FA',
    lane: 'MID',
    refreshedAt: '2022-06-02',
  },
  {
    playerId: 'Trap',
    name: '신승민',
    before: 'RENSGA',
    beforeShort: '',
    beforeLeague: 'CBLOL',
    after: 'FA',
    lane: 'TOP',
    refreshedAt: '2022-05-30',
  },
  {
    playerId: 'Mocha',
    name: '김태겸',
    before: 'RENSGA',
    beforeShort: '',
    beforeLeague: 'CBLOL',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-07-04',
  },
  {
    playerId: 'Guard',
    name: '하한결',
    before: 'RENSGA',
    beforeShort: '',
    beforeLeague: 'CBLOL',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-03-19',
  },
  {
    playerId: 'Hades',
    name: '박지성',
    before: 'RENSGA',
    beforeShort: '',
    beforeLeague: 'CBLOL',
    after: 'FA',
    lane: 'BOT',
    refreshedAt: '2022-03-19',
  },
  {
    playerId: 'Haru',
    name: '강민승',
    before: 'Team Vitality',
    beforeShort: '',
    beforeLeague: 'LEC',
    after: 'FA',
    lane: 'JUN',
    refreshedAt: '2022-10-30',
  },
  {
    playerId: 'Arthur',
    name: '박미르',
    before: 'The Chiefs',
    beforeShort: '',
    beforeLeague: 'LCO',
    after: 'FA',
    lane: 'JUN',
    refreshedAt: '2022-10-30',
  },
  {
    playerId: 'Patch',
    name: '한승민',
    before: 'Thunder Talk Gaming',
    beforeShort: '',
    beforeLeague: 'LPL',
    after: 'FA',
    lane: 'SUP',
    refreshedAt: '2022-06-01',
  },
  {
    playerId: 'Chasy',
    name: '김동현',
    before: 'X7 Esports',
    beforeShort: 'X7',
    beforeLeague: 'EM',
    after: 'FA',
    lane: 'TOP',
    refreshedAt: '2022-10-30',
  },
  {
    playerId: 'Tempt',
    name: '강명구',
    before: 'X7 Esports',
    beforeShort: '',
    beforeLeague: 'EM',
    after: 'FA',
    lane: 'MID',
    refreshedAt: '2022-10-30',
  },
  {
    playerId: 'Archer',
    name: '이근희',
    before: 'XTEN Esports',
    beforeShort: '',
    beforeLeague: 'LLA',
    after: 'FA',
    lane: 'BOT',
    refreshedAt: '2022-04-21',
  },
];

export default Transfer;
